name: CI Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  presubmit:
    name: CI Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build github.com/downflux/go-pq
      run: go build github.com/downflux/go-pq/...

    - name: Build github.com/downflux/go-pq
      run: go vet github.com/downflux/go-pq/...

    - name: Test github.com/downflux/go-pq
      run: go test github.com/downflux/go-pq/...
